FROM node:22-alpine AS frontend-builder
WORKDIR /app

COPY ./frontend/package*.json ./
RUN npm install

COPY ./frontend ./
RUN npm run build

FROM maven:3.8-openjdk-15 AS backend-builder
WORKDIR /backend

COPY ./backend/pom.xml .
COPY ./backend/src ./src

COPY --from=frontend-builder /app/dist/hdu-web/browser/ ./src/main/resources/static/

RUN mvn clean package -DskipTests

FROM tomcat:8.5-jdk15-openjdk-oracle

ENV APP_DATA_FOLDER=/var/lib/adaptor
ENV SAMPLE_APP_CONFIG=${APP_DATA_FOLDER}/config/

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=backend-builder /backend/target/icare-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war

WORKDIR $APP_DATA_FOLDER

EXPOSE 8080
ENTRYPOINT ["catalina.sh", "run"]