version: '3.4'

services:

  db:
    restart: "always"
    image: mariadb:10.4
    ports:
      - "3308:3306"
    environment:
      MARIADB_DATABASE: ${MARIADB_DB:-unified}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-Admin123}
      MARIADB_USER: ${MARIADB_USER:-unified}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-Admin123}
    healthcheck:
      test: "exit 0"
    #volumes:
    #    - ./test/backup/test.openmrs.sql.gz:/docker-entrypoint-initdb.d/database.sql.gz
  adapter:
    restart: "always"
    image: udsmdhis2/unified:latest
    environment: 
      DB_HOST: db
      DB_NAME: unified
      DB_PASSWORD: Admin123
    ports:
        - 8080:8080
    depends_on:
        - db
#   nginx:
#     image: nginx:1.17.9-alpine
#     env_file:
#       - .env
#     ports:
#       - 80:80
#     restart: always
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  potal-db:
    driver: local