import {
  ApartmentOutline,
  DashboardOutline,
  MergeOutline,
  UnorderedListOutline,
  UserOutline,
  LogoutOutline,
  AppstoreOutline,
  ScheduleOutline,
  DatabaseOutline,
  SnippetsOutline,
  ToolOutline,
  SettingOutline,
  InteractionOutline,
} from '@ant-design/icons-angular/icons';

export const antDesignIcons: any[] = [
  UserOutline,
  UnorderedListOutline,
  MergeOutline,
  ApartmentOutline,
  DashboardOutline,
  LogoutOutline,
  AppstoreOutline,
  ScheduleOutline,
  DatabaseOutline,
  SnippetsOutline,
  ToolOutline,
  SettingOutline,
  InteractionOutline,
];
