package com.Adapter.icare.Enums;

public enum MannerOfDeath {
    DISEASE,
    ACCIDENT,
    WAR,
    SUICIDE,
    UNKNOWN,
    DEATH_SENTENCE,
    ATTACKED,
    INVESTIGATION_IN_PROGRESS,
    TO_HANG_ONESELF_WITHOUT_KNOWN_CAUSES,
    UNRECOGNIZED_MANNER_OF_DEATH
}

