export enum MappingsUrls {
  GET_DATASETS_REMOTE = 'dataSets/remote',
  GET_DATASETS_SELECTED = 'dataSets',
  GET_DATASET_BY_ID = 'dataSets',
  GET_PROGRAMS_REMOTE = 'programs/remote',
  CONFIGURATIONS = 'hduApi/configurations',
  GET_ICD_CODES = 'hduApi/codeSystems/icd/codes',
  GET_LOINC_CODES = 'hduApi/codeSystems/loinc',
  GET_MSD_CODES = 'hduApi/generalCodes/msd',
  SELECT_DATASET_FOR_MAPPING = 'dataSets',
  REMOVE_DATASET_FROM_MAPPING = 'dataSets',
  GET_CATEGORY_OPTION_COMBO = 'dataElements',
  HDU_MAPPINGS = 'hduApi/mappings',
  HDU_PROGRAM_MAPPINGS = 'hduApi/mappings',
  GET_FLAT_VIEWS_TABLES = 'datastore/FLAT-VIEWS-TABLES',
}
